test

diff --git a/.github/workflows/code_checks.yml b/.github/workflows/code_checks.yml
--- a/.github/workflows/code_checks.yml
+++ b/.github/workflows/code_checks.yml
@@ -71,55 +71,56 @@ jobs:
           cp /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem config/ca-trust/
           docker cp config/ca-trust/VA-Internal-S2-RCA1-v1.cer.pem ${{ env.BUILDX_CONTAINER_ID }}:/usr/local/share/ca-certificates/
           docker exec -d  ${{ env.BUILDX_CONTAINER_ID }} update-ca-certificates
+          ls
 
-      - name: Build Docker Image
-        uses: docker/build-push-action@v2
-        with:
-          build-args: |
-            BUNDLE_ENTERPRISE__CONTRIBSYS__COM=${{ env.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}
-            USER_ID=${{ env.USER_ID }}
-          context: .
-          push: false
-          load: true
-          tags: vets-api:${{ env.DOCKER_IMAGE }}
-          cache-from: type=local,src=/tmp/.buildx-cache
-          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
+      # - name: Build Docker Image
+      #   uses: docker/build-push-action@v2
+      #   with:
+      #     build-args: |
+      #       BUNDLE_ENTERPRISE__CONTRIBSYS__COM=${{ env.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}
+      #       USER_ID=${{ env.USER_ID }}
+      #     context: .
+      #     push: false
+      #     load: true
+      #     tags: vets-api:${{ env.DOCKER_IMAGE }}
+      #     cache-from: type=local,src=/tmp/.buildx-cache
+      #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
 
-      - name: Move cache into place # This is to prevent the buildx cache from ballooning
-        run: |
-          rm -rf /tmp/.buildx-cache
-          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
+      # - name: Move cache into place # This is to prevent the buildx cache from ballooning
+      #   run: |
+      #     rm -rf /tmp/.buildx-cache
+      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
 
-      - name: Setup Database and Run Specs
-        run: |
-             docker-compose -p ${{ env.DOCKER_IMAGE}} run --rm --service-ports web bash \
-             -c "RAILS_ENV=test DISABLE_BOOTSNAP=true; \
-             bundle exec parallel_test -n 14 -e 'bundle exec rails db:reset' \
-             && bundle exec parallel_rspec spec/ modules/ -n 14 -o '--color --tty'"
+      # - name: Setup Database and Run Specs
+      #   run: |
+      #        docker-compose -p ${{ env.DOCKER_IMAGE}} run --rm --service-ports web bash \
+      #        -c "RAILS_ENV=test DISABLE_BOOTSNAP=true; \
+      #        bundle exec parallel_test -n 14 -e 'bundle exec rails db:reset' \
+      #        && bundle exec parallel_rspec spec/ modules/ -n 14 -o '--color --tty'"
 
-      - name: Upload Coverage Report
-        uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          name: Coverage Report
-          path: coverage
+      # - name: Upload Coverage Report
+      #   uses: actions/upload-artifact@v2
+      #   if: always()
+      #   with:
+      #     name: Coverage Report
+      #     path: coverage
 
-      - name: Upload Test Results
-        uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          name: Test Results
-          path: log/*.xml
-          if-no-files-found: ignore
+      # - name: Upload Test Results
+      #   uses: actions/upload-artifact@v2
+      #   if: always()
+      #   with:
+      #     name: Test Results
+      #     path: log/*.xml
+      #     if-no-files-found: ignore
 
-      - name: Cleanup
-        if: always()
-        run: |
-          docker rmi -f vets-api:${{ env.DOCKER_IMAGE }} 2> /dev/null || true
-          docker rm -f ${{ env.DOCKER_IMAGE }}-postgres-1 2> /dev/null || true
-          docker rm -f ${{ env.DOCKER_IMAGE }}-clamav-1  2> /dev/null || true
-          docker rm -f ${{ env.DOCKER_IMAGE }}-redis-1 2> /dev/null || true
-          chown ${{ env.USER_ID }} /data
+      # - name: Cleanup
+      #   if: always()
+      #   run: |
+      #     docker rmi -f vets-api:${{ env.DOCKER_IMAGE }} 2> /dev/null || true
+      #     docker rm -f ${{ env.DOCKER_IMAGE }}-postgres-1 2> /dev/null || true
+      #     docker rm -f ${{ env.DOCKER_IMAGE }}-clamav-1  2> /dev/null || true
+      #     docker rm -f ${{ env.DOCKER_IMAGE }}-redis-1 2> /dev/null || true
+      #     chown ${{ env.USER_ID }} /data
 
   publish_results:
     name: Publish Results
